#ifndef __AX_H__
#define __AX_H__

#include <stdint.h>

enum {
	AP_TX_BUF_OFFS_HI,
	AP_TX_BUF_OFFS_LO,
	AP_RX_BUF_OFFS_HI,
	AP_RX_BUF_OFFS_LO,
	AP_DSP_PROG_OFFS_HI,
	AP_DSP_PROG_OFFS_LO,
	AP_DSP_PARAM_OFFS_HI,
	AP_DSP_PARAM_OFFS_LO,
	AP_DSP_UPLOAD,
	AP_DSP_SET_LOWPASS,
	AP_DSP_SET_VOLUMES,
	AP_DSP_SET_PREFACTOR,
	AP_DSP_SET_EQ_BAND1,
	AP_DSP_SET_EQ_BAND2,
	AP_DSP_SET_EQ_BAND3,
	AP_DSP_SET_EQ_BAND4,
	AP_DSP_SET_EQ_BAND5,
	AP_DSP_SET_EQ_BAND6,
	AP_DSP_SET_EQ_BAND7,
	AP_DSP_SET_EQ_BAND8,
	AP_DSP_SET_EQ_BAND9,
	AP_DSP_SET_EQ_BAND10,
	AP_DSP_SET_STEREO_VOLUME,
	ZZ_NUM_AUDIO_PARAMS
};

#endif

