#!/bin/sh
set -eu

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH='' cd -- "$script_dir/.." && pwd)
status=0

cd "$repo_root"

make -C rtg/tests test
python3 -m unittest tools/tests/test_repo_tooling.py

if command -v shellcheck >/dev/null 2>&1; then
    shellcheck \
        tools/amiga-docker.sh tools/build-all.sh tools/package-local.sh \
        tools/check-release.sh tools/check-quality.sh tools/stage-zz9k-headers.sh \
        rtg/build.sh net/build.sh usb-poseidon/build.sh sd-boot/build.sh \
        ZZTop/build-gcc.sh \
        ahi/driver/build.sh ahi/axtest/build-gcc-single.sh \
        ahi/duplextest/build.sh mhi/build.sh \
        ZZDiag/build.sh || status=$?
else
    echo "SKIP: shellcheck not installed"
fi

if command -v actionlint >/dev/null 2>&1; then
    actionlint .github/workflows/ci.yml || status=$?
else
    echo "SKIP: actionlint not installed"
fi

# ZZ9000.CFG keys must agree across both repos - see check-cfg-keys.sh. Needs
# a firmware checkout, so it is skipped when there is not one; CI always has
# one and runs it there.
if [ -r "${ZZ9K_FIRMWARE_DIR:-../zz9000-firmware}/ZZ9000.CFG" ]; then
    tools/check-cfg-keys.sh || status=$?
else
    echo "SKIP: no firmware checkout (ZZ9000.CFG key check)"
fi

# The ZZTop icon is a committed binary generated by a script. Verify the
# committed bytes still match what the script produces, so the artwork stays
# reviewable as source rather than becoming an opaque blob nobody dares edit.
if command -v python3 >/dev/null 2>&1; then
    python3 tools/make-zztop-icon.py --check || status=$?
else
    echo "SKIP: python3 not installed (ZZTop icon check)"
fi

if command -v cppcheck >/dev/null 2>&1; then
    cppcheck --enable=warning,style,performance,portability \
        --error-exitcode=1 --suppress=missingIncludeSystem \
        -Iinclude -Irtg rtg/tests/register_cache_test.c ZZDiag/ZZDiag.c || status=$?
else
    echo "SKIP: cppcheck not installed"
fi

exit "$status"
